function(printConfiguration)
    message("")
    message("    _______________________________________________________________________ ")
    message("   |                                                                       |")
    message("   |                                 gstart                                |")
    message("   |_______________________________________________________________________|")
    message("                                                                            ")
    message("                                  Configuration                             ")
    message("             CMAKE_DEFAULT_BUILD_TYPE:     ${CMAKE_DEFAULT_BUILD_TYPE}      ")
    message("                     CMAKE_BUILD_TYPE:     ${CMAKE_BUILD_TYPE}              ")
    message("                                                                            ")
    message("   _________________________________________________________________________")
    message("")
endfunction(printConfiguration)

function(findSFML)
message("   function findSFML | curr path :${CMAKE_SOURCE_DIR}")
find_package(SFML PATHS "${CMAKE_SOURCE_DIR}/libs/SFML-2.5.1" NO_DEFAULT_PATH COMPONENTS graphics window system REQUIRED)
    set(SFML_STATIC_LIBRARIES true)
set(SFML_BUILD_GRAPHICS true)
set(SFML_BUILD_NETWORK true)
set(SFML_BUILD_WINDOW true)
set(SFML_BUILD_AUDIO true)
endfunction(findSFML)

function(findBoost)
find_package(Boost)
message(STATUS "Boost version: ${Boost_VERSION}")
endfunction(findBoost)

function(findEigen)
find_package(Eigen3 REQUIRED)
message(STATUS "Eigen3 version: ${Eigen3_VERSION}")
endfunction(findEigen)

function(buildTests)
enable_testing()
include(GoogleTest)
file(GLOB TEST_FILES ${CMAKE_CURRENT_SOURCE_DIR}/test/Test*)
foreach(test_file ${TEST_FILES})
    get_filename_component(exe_dst_name ${test_file} NAME_WLE)
    add_executable(${exe_dst_name} ${test_file})
    target_include_directories(${exe_dst_name} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include)
    target_link_libraries(${exe_dst_name} PRIVATE gtest_main shapes SFML::Graphics)
    gtest_discover_tests(${exe_dst_name})
endforeach()
endfunction(buildTests)

function(addLibs)
file(GLOB libs RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/libs/*)
foreach(lib ${libs})
    add_subdirectory(${lib})
endforeach()
endfunction(addLibs)

function(runCppCheck)
find_program(CMAKE_CXX_CPPCHECK NAMES cppcheck)
if (CMAKE_CXX_CPPCHECK)
list(
    APPEND CMAKE_CXX_CPPCHECK 
        "./src/"
        "--verbose"
)
endif()
endfunction(runCppCheck)
